[Interface]
PrivateKey = sKwuXg4n6A6Y6d0ASqoZADxGDsde5PihbqKu2uca6VA=
Address = 10.10.10.3/24
DNS = 1.1.1.1

[Peer]
PublicKey = qHUDKMrpCDfa9pUF9812fuqmTepvKqmBGRSfBYU6M3w=
Endpoint = 10.0.0.28:51820
AllowedIPs = 10.10.10.0/24, 192.168.1.0/24, 192.168.2.0/24
PersistentKeepalive = 25